### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by JADSN1894** [concoct-rs/concoct#50]
Hey, this is an excellent project! What are the differences between [concoct](https://github.com/concoct-rs) and [viewbuilder](https://github.com/matthunz/viewbuilder)?

**Comment by matthunz** [comment]
Thanks! I'm hoping to eventually transition Viewbuilder to become the native backend for this crate (and hopefully others).

The problem I'm still stuck with is an ergonomic way to write rust UI (which is why Viewbuilder is currently just another reactive system). Pretty much every variation I've tried has led me to think a xilem-style UI is our best best. I'd love to have this crate be a cross platform version of that architecture, but I'm not sure what that'd look like yet
